name: GitHub Actions Demo

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
        run: |
          if["$SECRET_HELLO" -eq "Hello Gursharn"]
            then 
               echo "Got Secret"
           fi     
        env:
          HELLO_SECRET: ${{ secrets.SECRET_HELLO }}         