name: GitHub Actions Demo

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test 
        run: |
          if [ "$SECRET_HELLO" == "Hello Gursharn" ]
            then 
               echo "Got Secret"
           fi     
        env:
          HELLO_SECRET: ${{ secrets.SECRET_HELLO }}         