# This is a basic workflow that is manually triggered

 

name: ⚙️🌐⚗️ Manual/Automated Build workflow

 

# Controls when the action will run. Workflow runs when manually triggered using the UI

# or API.

on:

  push:

    branches:

    - 'feature/**'

    - master

    - develop

   

  pull_request:

    branches:

      - develop

      - master

 

env:

  appname: example-git-secret

  organization: cb

  DEPLOY_SNAPSHOTS: false

  BRANCH_NAME     : ${{ GITHUB.REF }}

  SHOULD_BUILD    : ${{ GITHUB.REF == 'refs/heads/master' }}

 

jobs:

  initialize:

    name: Initialize

    runs-on: ubuntu-latest

   

    steps:

    - name: Initialize

      run: |

        echo "readMavenPom pom.xml"

        echo "BRANCH: $BRANCH_NAME"

        echo "SHOULD_BUILD: $SHOULD_BUILD"

 

  buildAndTest:

    name: Building code

    runs-on: ubuntu-latest

   

    steps:

    - uses: actions/checkout@v1

   

    - name: Set up JDK 11.0.4

      uses: actions/setup-java@v1

      with:

        java-version: 11.0.4

       

    - name: Set up Maven Settings

      uses: s4u/maven-settings-action@v2.4.0

   

 

    - name: Cache Maven packages

      uses: actions/cache@v2

      with:

        path: ~/.m2

        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

        restore-keys: ${{ runner.os }}-m2

 

    - name: Build

      id: build

      if: ${{ env.SHOULD_BUILD == true }}

      run:  |

        echo "Deploy snapshots: $DEPLOY_SNAPSHOTS"

        mvn --batch-mode --update-snapshots compile

       

    - name: JUnit

      id: junit

      run: mvn --batch-mode --update-snapshots test

      

  staticAnalysis:

    name: Static Analysis

    runs-on: ubuntu-latest

   

    steps:

      - name: Static Analysis

        run: echo "echo 'No static analysis configured for this project'"