name: GitHub Actions Demo

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          SECRET_HELLO: ${{ secrets.SECRET_HELLO }}
          run: echo "The selected color is ${{ secrets.SECRET_HELLO  }}"
 